INSERT INTO COMPETENCE VALUES (1, 'Développeur JAVA', 'DevJava');
INSERT INTO COMPETENCE VALUES (2, 'Développeur C', 'DevC');
INSERT INTO COMPETENCE VALUES (3, 'Développeur PHP', 'DevPHP');
INSERT INTO COMPETENCE VALUES (4, 'Développeur C++', 'DevC++');
INSERT INTO COMPETENCE VALUES (5, 'Développeur Javascript', 'DevJavaScript');
INSERT INTO COMPETENCE VALUES (6, 'Scrum master', 'Scrum');

INSERT INTO EQUIPE VALUES (1, 'Ekip667');
INSERT INTO EQUIPE VALUES (2, 'Equipe2');
INSERT INTO EQUIPE VALUES (3, 'LaTeam');

INSERT INTO CANDIDAT VALUES (1, 'Collaborateur', 'Dias', 'Nathan', 0, 0, 1);
INSERT INTO CANDIDAT VALUES (2, 'Collaborateur', 'aaa', 'zzz', 0, 0, 1);
INSERT INTO CANDIDAT VALUES (3, 'Collaborateur', 'bbb', 'yyy', 1, 0, 2);
INSERT INTO CANDIDAT VALUES (4, 'Collaborateur', 'ccc', 'xxx', 1, 1, 2);
INSERT INTO CANDIDAT VALUES (5, 'Collaborateur', 'ddd', 'www', 0, 1, 2);
INSERT INTO CANDIDAT VALUES (6, 'Collaborateur', 'eee', 'vvv', 0, 1, 3);
INSERT INTO CANDIDAT(ID, DTYPE, NOM, PRENOM) VALUES (7, 'Candidat', 'fff', 'uuu');
INSERT INTO CANDIDAT(ID, DTYPE, NOM, PRENOM) VALUES (8, 'Candidat', 'ggg', 'ttt');
INSERT INTO CANDIDAT(ID, DTYPE, NOM, PRENOM) VALUES (9, 'Candidat', 'hhh', 'sss');

INSERT INTO CANDIDAT_COMPETENCE VALUES (1, 1);
INSERT INTO CANDIDAT_COMPETENCE VALUES (1, 2);
INSERT INTO CANDIDAT_COMPETENCE VALUES (1, 6);
INSERT INTO CANDIDAT_COMPETENCE VALUES (2, 1);
INSERT INTO CANDIDAT_COMPETENCE VALUES (3, 1);
INSERT INTO CANDIDAT_COMPETENCE VALUES (3, 6);
INSERT INTO CANDIDAT_COMPETENCE VALUES (4, 2);
INSERT INTO CANDIDAT_COMPETENCE VALUES (4, 4);
INSERT INTO CANDIDAT_COMPETENCE VALUES (5, 3);
INSERT INTO CANDIDAT_COMPETENCE VALUES (5, 4);
INSERT INTO CANDIDAT_COMPETENCE VALUES (5, 5);

INSERT INTO DEMANDECOMPETENCE VALUES (1, 1, 1);
INSERT INTO DEMANDECOMPETENCE VALUES (2, 1, 2);
INSERT INTO DEMANDECOMPETENCE VALUES (3, 1, 2);
INSERT INTO DEMANDECOMPETENCE VALUES (4, 1, 2);
INSERT INTO DEMANDECOMPETENCE VALUES (5, 1, 2);

INSERT INTO DEMANDECOMPETENCE_COMPETENCE VALUES (1, 2);
INSERT INTO DEMANDECOMPETENCE_COMPETENCE VALUES (2, 2);
INSERT INTO DEMANDECOMPETENCE_COMPETENCE VALUES (3, 1);
INSERT INTO DEMANDECOMPETENCE_COMPETENCE VALUES (4, 1);
INSERT INTO DEMANDECOMPETENCE_COMPETENCE VALUES (6, 3);
INSERT INTO DEMANDECOMPETENCE_COMPETENCE VALUES (5, 4);
INSERT INTO DEMANDECOMPETENCE_COMPETENCE VALUES (4, 5);

INSERT INTO FICHEPOSTE VALUES (1, 0, 'MIAGE', 'Clown', 2);

INSERT INTO CANDIDATURE VALUES (1, 2, 7, 1);
INSERT INTO CANDIDATURE VALUES (2, 2, 8, 1);

UPDATE SEQUENCE
  SET SEQ_COUNT = 50 WHERE SEQ_NAME='SEQ_GEN';