package fr.miage.views;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import fr.andrea.christophe.m1.jee.miage_jee.shr.interfremote.ExpoLrdRemote;
import fr.andrea.christophe.m1.jee.miage_jee.shr.utilities.CollaborateurExport;
import fr.andrea.christophe.m1.jee.miage_jee.shr.utilities.CompetenceExport;
import fr.andrea.christophe.m1.jee.miage_jee.shr.utilities.DemandeCompetenceExport;
import fr.miage.controllers.CompetenceController;
import fr.miage.controllers.CompetencesDemandesController;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author ddias
 */
public class MainFrame extends javax.swing.JFrame {

    CompetencesDemandesController competencesDemandesController;
    CompetenceController competenceController;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        try {
            InitialContext ctx = new InitialContext();
            ExpoLrdRemote expoLrdRemote = (ExpoLrdRemote) ctx.lookup("fr.andrea.christophe.m1.jee.miage_jee.shr.interfremote.ExpoLrdRemote");
            this.competencesDemandesController = new CompetencesDemandesController(expoLrdRemote);
            this.competenceController = new CompetenceController(expoLrdRemote);
            initComponents();
        } catch (NamingException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listeCompetencesCollaborateurButton = new javax.swing.JButton();
        redigerFichePosteButton = new javax.swing.JButton();
        gérerCandidaturesbutton = new javax.swing.JButton();
        concretiserEmbaucheButton = new javax.swing.JButton();
        listeDemandeCompetencesButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listeCompetencesCollaborateurButton.setText("Lister competences des collaborateurs");
        listeCompetencesCollaborateurButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeCompetencesCollaborateurButtonActionPerformed(evt);
            }
        });

        redigerFichePosteButton.setText("Rediger fiche de poste");
        redigerFichePosteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redigerFichePosteButtonActionPerformed(evt);
            }
        });

        gérerCandidaturesbutton.setText("Gérer candidature");
        gérerCandidaturesbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gérerCandidaturesbuttonActionPerformed(evt);
            }
        });

        concretiserEmbaucheButton.setText("Concrétiser embauche");
        concretiserEmbaucheButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concretiserEmbaucheButtonActionPerformed(evt);
            }
        });

        listeDemandeCompetencesButton.setText("Lister demandes compétences des équipes");
        listeDemandeCompetencesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeDemandeCompetencesButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listeDemandeCompetencesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(concretiserEmbaucheButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gérerCandidaturesbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redigerFichePosteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listeCompetencesCollaborateurButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(listeDemandeCompetencesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(listeCompetencesCollaborateurButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(redigerFichePosteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gérerCandidaturesbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(concretiserEmbaucheButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void concretiserEmbaucheButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concretiserEmbaucheButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_concretiserEmbaucheButtonActionPerformed

    private void gérerCandidaturesbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gérerCandidaturesbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gérerCandidaturesbuttonActionPerformed

    private void redigerFichePosteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redigerFichePosteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redigerFichePosteButtonActionPerformed

    private void listeCompetencesCollaborateurButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeCompetencesCollaborateurButtonActionPerformed
        HashMap<CollaborateurExport, ArrayList<CompetenceExport>> listeCompetencesCollaborateurs = this.competenceController.listerCompetencesCollaborateurs();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Nom");
        model.addColumn("Prenom");
        model.addColumn("Competences");
        this.jTable1.setModel(model);

        for(CollaborateurExport cle : listeCompetencesCollaborateurs.keySet()){
            DefaultTableModel tableModel = (DefaultTableModel) this.jTable1.getModel();
            StringBuilder competences = new StringBuilder();
            for(CompetenceExport ce : listeCompetencesCollaborateurs.get(cle)){
                competences.append(ce.getNom()).append(" ; ");
            }
            tableModel.addRow(new Object[]{cle.getId(), cle.getNom(), cle.getPrenom(), competences.toString()});
        }

    }//GEN-LAST:event_listeCompetencesCollaborateurButtonActionPerformed

    private void listeDemandeCompetencesButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                              
        HashSet<DemandeCompetenceExport> demandeCompetenceExports = this.competencesDemandesController.listerCompetencesDemandeesEquipes();

        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id");
        model.addColumn("Etat");
        model.addColumn("DemandeCompetences");
        model.addColumn("Equipe");
        this.jTable1.setModel(model);
        
        for(DemandeCompetenceExport dce : demandeCompetenceExports){
            DefaultTableModel tableModel = (DefaultTableModel) this.jTable1.getModel();
            StringBuilder competences = new StringBuilder();
            for(CompetenceExport ce : dce.getCompetenceExportList()){
                competences.append(ce.getNom()).append(" ; ");
            }
            tableModel.addRow(new Object[]{dce.getId(), dce.getEtat(), competences.toString(), dce.getEquipeExport().getId()});
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton concretiserEmbaucheButton;
    private javax.swing.JButton gérerCandidaturesbutton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton listeCompetencesCollaborateurButton;
    private javax.swing.JButton listeDemandeCompetencesButton;
    private javax.swing.JButton redigerFichePosteButton;
    // End of variables declaration//GEN-END:variables
}
